# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=greenteagc
  targets:
  - darwin_arm64
  - darwin_arm64_v8.4 # Apple M1
  - darwin_arm64_v8.6 # Apple M2/M3
  - darwin_arm64_v9.2 # Apple M4
  - freebsd_amd64
  - freebsd_arm64
  - linux_amd64
  - linux_amd64_v2
  - linux_amd64_v3
  - linux_amd64_v4
  - linux_arm_v6
  - linux_arm_v7
  - linux_arm64
  - linux_arm64_v8.0
  - linux_arm64_v8.2 # Graviton2 / Raspberry Pi 5
  - linux_arm64_v8.4 # Graviton3
  - linux_arm64_v9.0 # Graviton4
  - linux_arm64_v9.2
  - openbsd_amd64
  - openbsd_arm64
  - windows_amd64
  - windows_amd64_v2
  - windows_amd64_v3
  - windows_amd64_v4
  - windows_arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w
  binary: |-
    {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
    {{- if .Arm }}
      {{- .Arm }}
    {{- else if and .Arm64 (ne .Arm64 "v8.0") }}
      {{- .Arm64 }}
    {{- else if and .Amd64 (ne .Amd64 "v1") }}
      {{- .Amd64 }}
    {{- end }}
  no_unique_dist_dir: true
archives:
- name_template: |-
    {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
    {{- if .Arm }}
      {{- .Arm }}
    {{- else if and .Arm64 (ne .Arm64 "v8.0") }}
      {{- .Arm64 }}
    {{- else if and .Amd64 (ne .Amd64 "v1") }}
      {{- .Amd64 }}
    {{- end }}
  formats:
  - binary
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: sylr
    name: hey
