# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GOEXPERIMENT=greenteagc
  goos:
  - linux
  - freebsd
  - openbsd
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  - "7"
  goamd64:
  - v1
  - v2
  - v3
  - v4
  goarm64:
  - v8.0
  - v8.1
  - v8.2
  - v8.3
  - v9.0
  ignore:
  - goos: windows
    goarch: arm
  flags:
  - -trimpath
  ldflags:
  - -s -w
archives:
- name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ else if .Arm64 }}{{ .Arm64 }}{{ else if .Amd64 }}{{ .Amd64 }}{{ end }}"
  formats:
  - binary
checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: sylr
    name: hey
